set(DEPENDENCIES_VERSION 1.1.0)
caffe_option(USE_PREBUILT_DEPENDENCIES "Download and use the prebuilt dependencies" ON IF MSVC)
if(MSVC)
  file(TO_CMAKE_PATH $ENV{USERPROFILE} USERPROFILE_DIR)
  if(NOT EXISTS ${USERPROFILE_DIR})
    message(FATAL_ERROR "Could not find %USERPROFILE% directory. Please specify an alternate CAFFE_DEPENDENCIES_ROOT_DIR")
  endif()
  set(CAFFE_DEPENDENCIES_ROOT_DIR  CACHE PATH "Prebuild depdendencies root directory")
endif()
if(USE_PREBUILT_DEPENDENCIES)
    # Determine the python version
    if(BUILD_python)
        if(NOT PYTHONINTERP_FOUND)
            if(NOT "${python_version}" VERSION_LESS "3.0.0")
                find_package(PythonInterp 3.5)
            else()
                find_package(PythonInterp 2.7)
            endif()
        endif()
        set(_pyver ${PYTHON_VERSION_MAJOR}${PYTHON_VERSION_MINOR})
    else()
        message(STATUS "Building without python. Prebuilt dependencies will default to Python 2.7")
        set(_pyver 27)
    endif()

    if(EXISTS ${CAFFE_DEPENDENCIES_ROOT_DIR}/caffe-builder-config.cmake)
        include(${CAFFE_DEPENDENCIES_ROOT_DIR}/caffe-builder-config.cmake)
    else()
        message(FATAL_ERROR "Something went wrong while dowloading dependencies could not open caffe-builder-config.cmake")
    endif()
endif()

